[site]
bucket = "./.next"
entry-point = "."

[build]
command = "npx next build"
output_directory = ".next"

[build.upload]
format = "service-worker"

[env.production]
name = "slur_id-production"
route = ""

[env.staging]
name = "slur_id-staging"
route = "" 